name: Deploy
run-name: Deploy ${{ github.ref_name }}

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Write GitHub context to log
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v3

      - run: dotnet publish -c Release -o out
        working-directory: src/HelloWorld
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: HelloWorld_${{ github.ref_name }}
          path: out
        
  deploy-prd:
    needs: build
    environment: prd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: HelloWorld_${{ github.ref_name }}
          path: in

      - run: dotnet HelloWorld.dll
        working-directory: in
