name: Deploy
run-name: Deploy ${{ github.ref_name }}

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: "Hello"
      output2: "World"
    steps:
      - run: |
          echo "ASD='Hello World'" >> "$GITHUB_ENV"
          echo $ASD
      - run: echo ${{ env.ASD }}


  # deploy-prd:
  #   environment: prd
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Write GitHub context to log
  #       env:
  #         GITHUB_CONTEXT: ${{ toJSON(github) }}
  #       run: echo "$GITHUB_CONTEXT"

  #     - run: printenv

  #     - run: printenv
  #     - run: echo "$MYJOBS"
  #       env:
  #         MYJOBS: ${{ toJSON(job) }}
  #     # - uses: actions/download-artifact@v4
  #     #   with:
  #     #     name: HelloWorld_${{ github.ref_name }}
  #     #     path: in

  #     # - run: dotnet HelloWorld.dll
  #     #   working-directory: in
