name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Write GitHub context to log
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: printenv
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: dotnet build
        working-directory: src/HelloWorld
    
      - uses: paulhatch/semantic-version@v5.4.0
        id: versioning
        with:
          tag_prefix: "v"
        if: ${{ github.event_name != 'pull_request'}}
        
      - name: Tag Release
        run: |
          git tag ${{ steps.versioning.outputs.version_tag }}
          echo "Added tag ${{ steps.versioning.outputs.version_tag }} for version ${{ steps.versioning.outputs.version }}"
          git push --tags
          echo "Pushed tag ${{ steps.versioning.outputs.version_tag }} to origin" 
        shell: bash
        if: ${{ github.event_name != 'pull_request'}}
