run-name: ${{inputs.version}}
name: deploy!

on:
  workflow_call:
    inputs:
      version:
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploying to ${{inputs.version}}"
