run-name: "ref: ${{github.ref}} - refname: ${{github.ref_name}}"
name: deploy!

on:
  push:
    tags: '*'
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploying to ${{inputs.version}}"
