name: Test fed creds

on:
  push:
    branches: ["main"]

env:
  val: "true"

jobs:
  login:
    permissions: 
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: 2023930d-2445-4d86-9995-fa122bfc7aaf
          tenant-id: 56219acc-ec33-4d2d-8f0e-76156d8e8010
          # subscription-id: cefaa5b6-8ccc-4b55-a658-549534c096c4

      - name: Run az commands
        run: |
          az account show
          az group list
        if: ${{ env.val == "true" }}

      - name: Azure Logout & Cleanup
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az logout
            az cache purge
            az account clear
