name: Test fed creds

on:
  push:
    branches: ["main"]

jobs:
  login:
    permissions: 
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          client-id: 2023930d-2445-4d86-9995-fa122bfc7aaf
          tenant-id: 56219acc-ec33-4d2d-8f0e-76156d8e8010

      - name: Run az commands
        run: |
          az account show
          az group list
      
      - name: Azure Logout & Cleanup
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az logout
            az cache purge
            az account clear
