name: git tags
run-name: "${{ env.val }} ${{github.workflow}} ${{github.run_number}} ${{github.run_attempt}}"

env:
  val: ";)"
on:
  push:
    paths: .github/workflows/gittags.yaml

jobs:
  thejob:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello World'
