name: git tags
run-name: "Build and push ${{ github.event.inputs.tag }}"
  
env:
  val: ";)"
on:
  push:
    paths: .github/workflows/gittags.yaml
  workflow_dispatch:
    
    
jobs:
  thejob:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello World'
