name: git tags
run-name: "${{ inputs.val }} ${{github.workflow}} ${{github.run_number}} ${{github.run_attempt}}"
  
env:
  val: ";)"
on:
  push:
    paths: .github/workflows/gittags.yaml
  workflow_dispatch:
    inputs:
      val:
        type: string
        default: "Hello World"
    
jobs:
  thejob:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello World'
